### ISSUE TITLE
No License specified

### ISSUE THREAD

**Issue by Wirack** [drorgl/cspatialindexrt#4]
I would like to use your RTree data structure for a project of mine, but see no license specified.

**Comment by drorgl** [comment]
The original code (https://sourceforge.net/projects/jsi/) is released under LGPLv2, so in theory this code should also be released under LGPLv2, since its a library, you shouldn't care about it unless you make modifications to it.

I've made so many modifications to it, I'm not sure how much of the original code is left in there.

In practice, you can always contact the original author and ask for clarifications.

**Comment by Wirack** [comment]
Thanks for the clarification!
